// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'features/home/data/models/recipe_model.dart';
import 'features/sync/data/models/sync_request_model.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 2033515626561921566),
    name: 'RecipeModel',
    lastPropertyId: const obx_int.IdUid(11, 6166398869829331420),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 1874518395235253124),
        name: 'id',
        type: 6,
        flags: 129,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 5415414297218198410),
        name: 'titleAr',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 3832070058332276774),
        name: 'titleEn',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 7623672300805170104),
        name: 'detailsAr',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 5226734236039575868),
        name: 'detailsEn',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 5229590827432738847),
        name: 'imageUrl',
        type: 30,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 1377134077449934751),
        name: 'createdAt',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 5294254334898132064),
        name: 'prepTime',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 4784173838478005051),
        name: 'servings',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 6054631607195949263),
        name: 'category',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 5403328925692380284),
    name: 'SyncRequestModel',
    lastPropertyId: const obx_int.IdUid(6, 4812908944211497633),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 6516694131455056184),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 7367721679487990028),
        name: 'method',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 691659674967575902),
        name: 'endpoint',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 555912304104331943),
        name: 'payloadJson',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 8012830067365520242),
        name: 'imagePath',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 4812908944211497633),
        name: 'recipeId',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(2, 5403328925692380284),
    lastIndexId: const obx_int.IdUid(0, 0),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [6166398869829331420],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    RecipeModel: obx_int.EntityDefinition<RecipeModel>(
      model: _entities[0],
      toOneRelations: (RecipeModel object) => [],
      toManyRelations: (RecipeModel object) => {},
      getId: (RecipeModel object) => object.id,
      setId: (RecipeModel object, int id) {
        object.id = id;
      },
      objectToFB: (RecipeModel object, fb.Builder fbb) {
        final titleArOffset = fbb.writeString(object.titleAr);
        final titleEnOffset = fbb.writeString(object.titleEn);
        final detailsArOffset = fbb.writeString(object.detailsAr);
        final detailsEnOffset = fbb.writeString(object.detailsEn);
        final imageUrlOffset = fbb.writeList(
          object.imageUrl.map(fbb.writeString).toList(growable: false),
        );
        final createdAtOffset = fbb.writeString(object.createdAt);
        final categoryOffset = fbb.writeString(object.category);
        fbb.startTable(12);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, titleArOffset);
        fbb.addOffset(2, titleEnOffset);
        fbb.addOffset(3, detailsArOffset);
        fbb.addOffset(4, detailsEnOffset);
        fbb.addOffset(5, imageUrlOffset);
        fbb.addOffset(6, createdAtOffset);
        fbb.addInt64(7, object.prepTime);
        fbb.addInt64(8, object.servings);
        fbb.addOffset(9, categoryOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final titleArParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final titleEnParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final detailsArParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final detailsEnParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final imageUrlParam = const fb.ListReader<String>(
          fb.StringReader(asciiOptimization: true),
          lazy: false,
        ).vTableGet(buffer, rootOffset, 14, []);
        final createdAtParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 16, '');
        final prepTimeParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          18,
          0,
        );
        final servingsParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          20,
          0,
        );
        final categoryParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 22, '');
        final object = RecipeModel(
          id: idParam,
          titleAr: titleArParam,
          titleEn: titleEnParam,
          detailsAr: detailsArParam,
          detailsEn: detailsEnParam,
          imageUrl: imageUrlParam,
          createdAt: createdAtParam,
          prepTime: prepTimeParam,
          servings: servingsParam,
          category: categoryParam,
        );

        return object;
      },
    ),
    SyncRequestModel: obx_int.EntityDefinition<SyncRequestModel>(
      model: _entities[1],
      toOneRelations: (SyncRequestModel object) => [],
      toManyRelations: (SyncRequestModel object) => {},
      getId: (SyncRequestModel object) => object.id,
      setId: (SyncRequestModel object, int id) {
        object.id = id;
      },
      objectToFB: (SyncRequestModel object, fb.Builder fbb) {
        final methodOffset = fbb.writeString(object.method);
        final endpointOffset = fbb.writeString(object.endpoint);
        final payloadJsonOffset = object.payloadJson == null
            ? null
            : fbb.writeString(object.payloadJson!);
        final imagePathOffset = object.imagePath == null
            ? null
            : fbb.writeString(object.imagePath!);
        fbb.startTable(7);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, methodOffset);
        fbb.addOffset(2, endpointOffset);
        fbb.addOffset(3, payloadJsonOffset);
        fbb.addOffset(4, imagePathOffset);
        fbb.addInt64(5, object.recipeId);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final methodParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final endpointParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final payloadJsonParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 10);
        final imagePathParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 12);
        final recipeIdParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          14,
        );
        final object = SyncRequestModel(
          id: idParam,
          method: methodParam,
          endpoint: endpointParam,
          payloadJson: payloadJsonParam,
          imagePath: imagePathParam,
          recipeId: recipeIdParam,
        );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [RecipeModel] entity fields to define ObjectBox queries.
class RecipeModel_ {
  /// See [RecipeModel.id].
  static final id = obx.QueryIntegerProperty<RecipeModel>(
    _entities[0].properties[0],
  );

  /// See [RecipeModel.titleAr].
  static final titleAr = obx.QueryStringProperty<RecipeModel>(
    _entities[0].properties[1],
  );

  /// See [RecipeModel.titleEn].
  static final titleEn = obx.QueryStringProperty<RecipeModel>(
    _entities[0].properties[2],
  );

  /// See [RecipeModel.detailsAr].
  static final detailsAr = obx.QueryStringProperty<RecipeModel>(
    _entities[0].properties[3],
  );

  /// See [RecipeModel.detailsEn].
  static final detailsEn = obx.QueryStringProperty<RecipeModel>(
    _entities[0].properties[4],
  );

  /// See [RecipeModel.imageUrl].
  static final imageUrl = obx.QueryStringVectorProperty<RecipeModel>(
    _entities[0].properties[5],
  );

  /// See [RecipeModel.createdAt].
  static final createdAt = obx.QueryStringProperty<RecipeModel>(
    _entities[0].properties[6],
  );

  /// See [RecipeModel.prepTime].
  static final prepTime = obx.QueryIntegerProperty<RecipeModel>(
    _entities[0].properties[7],
  );

  /// See [RecipeModel.servings].
  static final servings = obx.QueryIntegerProperty<RecipeModel>(
    _entities[0].properties[8],
  );

  /// See [RecipeModel.category].
  static final category = obx.QueryStringProperty<RecipeModel>(
    _entities[0].properties[9],
  );
}

/// [SyncRequestModel] entity fields to define ObjectBox queries.
class SyncRequestModel_ {
  /// See [SyncRequestModel.id].
  static final id = obx.QueryIntegerProperty<SyncRequestModel>(
    _entities[1].properties[0],
  );

  /// See [SyncRequestModel.method].
  static final method = obx.QueryStringProperty<SyncRequestModel>(
    _entities[1].properties[1],
  );

  /// See [SyncRequestModel.endpoint].
  static final endpoint = obx.QueryStringProperty<SyncRequestModel>(
    _entities[1].properties[2],
  );

  /// See [SyncRequestModel.payloadJson].
  static final payloadJson = obx.QueryStringProperty<SyncRequestModel>(
    _entities[1].properties[3],
  );

  /// See [SyncRequestModel.imagePath].
  static final imagePath = obx.QueryStringProperty<SyncRequestModel>(
    _entities[1].properties[4],
  );

  /// See [SyncRequestModel.recipeId].
  static final recipeId = obx.QueryIntegerProperty<SyncRequestModel>(
    _entities[1].properties[5],
  );
}
